### ISSUE TITLE
Add Bundle detection

### ISSUE THREAD

**Issue by RuinTD** [Liqutch/FNGG-LockerGenerator#1]
Hello. It would be nice if this program could detect bundles, probably just based on if the items in the bundle are owned.

**Comment by RuinTD** [comment]
It's worth noting that you can get a list of bundles and their items from https://fortnite.gg/api/bundles.json

**Comment by RuinTD** [comment]
Hello. I saw f19d09722275c08b5718b3f2868882b5bbc22dac and just need to point out a bit of quark with `bundles.json` I noticed. Bundles that include a skin with a built-in emote (such as the [Slim Shady Bundle](https://fortnite.gg/cosmetics?id=10774) listing the [Mask Up emote](https://fortnite.gg/cosmetics?id=10754)) won't count the bundle, since the Fortnite API doesn't list built-in emotes as being owned. In my fork, I detected this by using [Fortnite-API](https://fortnite-api.com/) and iterating every owned cosmetic for their built-in emotes, adding each one to the locker before adding bundles. :sob:

https://github.com/RuiNtD/FNGG-LockerGenerator/blob/379d2bb50a8e8adffae033a4b543a81c9ddd3055/src/index.ts#L59-L65

**Comment by RuinTD** [comment]
Oh also, it seems that "packs" (the bundles that can only be bought with real money and not with V-Bucks) aren't listed in `bundles.json`. Could not find a workaround for this. Fortnite-API doesn't have any mention of them either.

**Comment by Liqutch** [comment]
Done!

**Comment by Liqutch** [comment]
Thanks for the information, fixed that too!
