### ISSUE TITLE
Most banners aren't detected

### ISSUE THREAD

**Issue by RuinTD** [Liqutch/FNGG-LockerGenerator#2]
This program seems to miss most of the banners I own.
![image](https://github.com/user-attachments/assets/85486dfa-4811-4a2a-9f8a-06f0f9f82e27)
![image](https://github.com/user-attachments/assets/655474f0-b3bb-4394-9a9b-03be9f475513)
![image](https://github.com/user-attachments/assets/10ed3d87-a738-4d9c-aee2-9d44cdb8854c)

**Comment by Liqutch** [comment]
couldn't find banners data (except a few) bc they're not in QueryProfile response.

**Comment by RuinTD** [comment]
I suspect the data might be somewhere in the Save The World APIs.

**Comment by RuinTD** [comment]
Hey, found the endpoint! It's the same URL and output format as QueryProfile, but change profileId from athena to common_core (or just leave it blank) :)

Thanks to @LeleDerGrasshalmi for the documentation! :D
https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/tree/main/EpicGames/FN-Service/Game/Profile

The implementation in my fork:
- [EpicAPI.ts](https://github.com/RuiNtD/FNGG-LockerGenerator/blob/28baa1cdcf17880ab1126660faaea49b88e02753/src/EpicAPI.ts#L106-L119)
- [index.ts](https://github.com/RuiNtD/FNGG-LockerGenerator/blob/28baa1cdcf17880ab1126660faaea49b88e02753/src/index.ts#L37-L49)

**Comment by Liqutch** [comment]
Oh, didn't check `common_core` lmao. Also updated the code, thanks!
